name: Build and Deploy to GitHub Pages on Push

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          LIMITATION_SECRET: ${{ secrets.LIMITATION_SECRET }}
          BRANCH: gh-pages
          FOLDER: dist
          BUILD_SCRIPT: pnpm && yarn pnpm build
